- pipeline.id: atm
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-atm.conf"

- pipeline.id: en
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-en.conf"

- pipeline.id: geo
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-geo.conf"

- pipeline.id: img
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-img.conf"

- pipeline.id: naif
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-naif.conf"

- pipeline.id: ppi
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-ppi.conf"

- pipeline.id: rings
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-rings.conf"

- pipeline.id: sbn
  path.config: "$LS_SETTINGS_DIR/pipelines/pipeline-sbn.conf"
