log_directory: /report_service/logs/final
profile_name: saml-pub
s3_bucket: pds-web-analytics-cloud
s3_logdir: logs_dev
subdirs:
  atm:
    atm-apache-http:
      include:
        - "atm-atmos-apache.2022*.txt"
  en:
    en-http-pds-proxy:
      include:
        - "*.2022*.txt.gz"
    en-http-pdscloud-prod1:
      include:
        - "*.2023*.txt.gz"
        - "*.2022*.txt.gz"
    en-http-pdscloud-prod2:
      include:
        - "*.2023*.txt.gz"
        - "*.2022*.txt.gz"
  geo:
    geo-ode:
      include:
        - "u_ex22*"
    geo-ode-cart:
      include:
        - "u_ex22*"
    geo-pds:
      include:
        - "u_ex22*"
    geo-speclib:
      include:
        - "u_ex22*"
    geo-va:
      include:
        - "u_ex22*"
  img:
    img-pdsimage-http:
      include:
        - "*.2022*"
    img-pdsimg1-http:
      include:
        - "*.2022*"
    img-pdsimg2-http:
      include:
        - "*.2022*"
    img-pdsimg3-http:
      include:
        - "*.2022*"
  ppi:
    ppi-tomcat:
      include:
        - "*2022*.log.gz"
  rings:
    rings-apache-metrics:
      include:
        - "*.2021*.log"
  naif:
    naif-httpdlogs:
      include:
        - "naif_access_log.22*"
  sbn:
    sbn-apache-http:
      include:
        - "sbnumd2022*.log"
    sbn-psi-tomcat:
      include:
        - "sbn_archive_2022*.txt"
