log_directory: /report_service/logs/final
profile_name: saml-pub
s3_bucket: pds-web-analytics-cloud
s3_logdir: logs_dev_kai
subdirs:
  atm:
    atm-apache-http:
      include:
        - "atm-atmos-apache.2024*.txt"
  en:
    en-http-pds-proxy:
      include:
        - "*.2024*.txt.gz"
    en-http-pdscloud-prod1:
      include:
        - "*.2024*.txt.gz"
    en-http-pdscloud-prod2:
      include:
        - "*.2024*.txt.gz"
  geo:
    geo-ode:
      include:
        - "u_ex24*"
    geo-ode-cart:
      include:
        - "u_ex24*"
    geo-pds:
      include:
        - "u_ex24*"
    geo-speclib:
      include:
        - "u_ex24*"
    geo-va:
      include:
        - "u_ex24*"
  img:
    img-pdsimage-http:
      include:
        - "*.2024*"
    img-pdsimg1-http:
      include:
        - "*.2024*"
    img-pdsimg2-http:
      include:
        - "*.2024*"
    img-pdsimg3-http:
      include:
        - "*.2024*"
  ppi:
    ppi-tomcat:
      include:
        - "*2024*.log.gz"
  rings:
    rings-apache-metrics:
      include:
        - "*.2024*.log"
  naif:
    naif-httpdlogs:
      include:
        - "naif_access_log.24*"
  sbn:
    sbn-apache-http:
      include:
        - "sbnumd2024*.log"
    sbn-psi-tomcat:
      include:
        - "sbn_archive_2024*.txt"
