log_directory: /report_service/logs/final
profile_name: saml-pub
s3_bucket: pds-web-analytics-cloud
s3_logdir: logs
subdirs:
<<<<<<< HEAD
  atm:
    atm-apache-http:
      include:
        - "atm-atmos-apache.2023*.txt"
        - "atm-atmos-apache.2022*.txt"
        - "atm-atmos-apache.2021*.txt"
=======
>>>>>>> 2-local-aws-filesync-shell-mod
  en:
    en-http-pdscloud-prod1:
      include:
        - "*.2023*.txt.gz"
        - "*.2022*.txt.gz"
<<<<<<< HEAD
        - "*.2021*.txt.gz"
=======
>>>>>>> 2-local-aws-filesync-shell-mod
    en-http-pdscloud-prod2:
      include:
        - "*.2023*.txt.gz"
        - "*.2022*.txt.gz"
<<<<<<< HEAD
        - "*.2021*.txt.gz"
=======
>>>>>>> 2-local-aws-filesync-shell-mod
  geo:
    geo-ode:
      include:
        - "u_ex23*"
        - "u_ex22*"
        - "u_ex21*"
    geo-ode-cart:
      include:
        - "u_ex23*"
        - "u_ex22*"
        - "u_ex21*"
    geo-pds:
      include:
        - "u_ex23*"
        - "u_ex22*"
        - "u_ex21*"
    geo-speclib:
      include:
        - "u_ex23*"
        - "u_ex22*"
        - "u_ex21*"
    geo-va:
      include:
        - "u_ex23*"
        - "u_ex22*"
        - "u_ex21*"
  img:
    img-pdsimage-http:
      include:
        - "*.2023*"
        - "*.2022*"
        - "*.2021*"
    img-pdsimg1-http:
      include:
        - "*.2023*"
        - "*.2022*"
        - "*.2021*"
    img-pdsimg2-http:
      include:
        - "*.2023*"
        - "*.2022*"
        - "*.2021*"
    img-pdsimg3-http:
      include:
        - "*.2023*"
        - "*.2022*"
        - "*.2021*"
<<<<<<< HEAD
  ppi:
    ppi-tomcat:
      include:
        - "*2023*.log.gz"
        - "*2022*.log.gz"
        - "*2021*.log.gz"
  rings:
    rings-apache-metrics:
      include:
        - "*.2023*.log"
        - "*.2022*.log"
        - "*.2021*.log"
  naif:
    naif-httpdlogs:
      include:
        - "naif_access_log.23*"
        - "naif_access_log.22*"
        - "naif_access_log.21*"
  sbn:
    sbn-apache-http:
      include:
        - "sbnumd2023*.log"
        - "sbnumd2022*.log"
        - "sbnumd2021*.log"
    sbn-psi-tomcat:
      include:
        - "sbn_archive_2023*.txt"
        - "sbn_archive_2022*.txt"
        - "sbn_archive_2021*.txt"
=======
>>>>>>> 2-local-aws-filesync-shell-mod
