log_directory: /home/kaipak/datasets/report_service/logs/final
profile_name: saml-pub
s3_bucket: pds-web-analytics-cloud
s3_logdir: logs_dev
subdirs:
  geo:
    - geo-pds
  en:
    - en-http-pdscloud-prod1
    - en-http-pdscloud-prod2

