log_directory: /home/kaipak/datasets/report_service/logs/final
node_dirs: [geo]
profile_name: saml-pub
s3_bucket: pds-web-analytics-cloud
s3_logdir: logs
subdirs:
  geo:
    - geo-pds
  en:
    - en-http-pdsweb1
    - en-http-pdsweb2

